import { UnitDefinition } from '../types/portfolio';

export const UNITS_DATA: UnitDefinition[] = [
  {
    id: 1,
    code: '01',
    title: '동백 마들렌',
    moduleGroup: '모듈 1 · 클래식 구움과자 & 전통 퓨전',
    icon: '🧁',
    themeColor: 'teal',
    accentHex: '#0d9488',
    accentDarkHex: '#0f766e',
    softHex: '#f0fdfa',
    brief: '마들렌 반죽의 유화·휴지·균일 팬닝과 굽기 결과를 연결해 기록합니다.',
    goal: '반죽 온도와 휴지시간을 관리하고, 일정한 팬닝으로 동백 마들렌의 형태와 기공을 완성한다.',
    photoGuide: '윗면의 배꼽과 색이 보이는 사진 1장, 단면의 기공이 보이는 사진 1장을 권장합니다.',
    keyQuestions: ['반죽 휴지 시간과 배꼽 솟음의 상관관계는?', '팬닝량 편차에 따른 구움색 차이는?'],
    standardSteps: [
      '1. 버터를 중탕으로 녹여 45~50℃ 따뜻한 온도를 유지한다.',
      '2. 볼에 달걀과 설탕, 소금을 넣고 거품기로 설탕 서걱거림이 없을 때까지 부드럽게 섞는다 (공기 주입 자제).',
      '3. 체 친 박력분과 베이킹파우더를 넣고 매끄럽게 가루가 뭉치지 않도록 혼합한다.',
      '4. 녹인 버터를 2~3회 나누어 넣으며 매끄럽게 유화시킨 후 동백꽃 시럽을 넣고 섞는다.',
      '5. 볼을 밀착 랩핑하여 냉장고에서 최소 30분~1시간 차갑게 휴지(5℃ 이하)시킨다.',
      '6. 버터 칠한 마들렌 틀에 80%(32g) 팬닝 후 180℃ 예열 오븐에서 12~14분간 배꼽이 솟도록 굽는다.',
    ],
    flapTitle: '🌸 마들렌 배꼽(Bosse)의 비밀 & 열충격 과학',
    flapHint: '플랩을 열어 파티시에 시크릿 노하우를 확인하세요',
    flapContent: {
      secretTip: '반죽을 반드시 냉장고에서 최소 30분~1시간 차갑게 휴지(5℃ 이하)시킨 뒤, 180℃ 이상 예열된 뜨거운 오븐에 투입해야 극적인 열충격(Thermal Shock)으로 중앙 배꼽이 솟아오릅니다.',
      sciencePrinciple: '차가운 반죽 테두리가 먼저 익으면서 팽창 압력이 가운데로 집중되고, 베이킹파우더의 탄산가스와 수증기가 가운데로 분출하며 배꼽을 형성합니다.',
      goldenRule: '틀의 80%(약 30~32g)만 균일하게 팬닝하고, 오븐 첫 7분 동안은 문을 절대 열지 마세요.',
    },
    fields: [
      { key: 'formula', label: '표준 배합과 실제 계량', type: 'textarea', placeholder: '재료명과 실제 계량값을 기록하세요 (버터, 설탕, 박력분, 달걀 등).', fullWidth: true },
      { key: 'batterTemp', label: '혼합 후 반죽온도(℃)', type: 'number', placeholder: '예: 23', unitSuffix: '℃' },
      { key: 'restTime', label: '냉장 휴지시간(분)', type: 'number', placeholder: '예: 30', unitSuffix: '분' },
      { key: 'portionWeight', label: '한 개당 팬닝량(g)', type: 'number', placeholder: '예: 32', unitSuffix: 'g' },
      { key: 'bakeCondition', label: '윗불·아랫불·굽기시간', type: 'text', placeholder: '예: 180℃ / 160℃ / 13분' },
      { key: 'quality', label: '배꼽·색·단면 기공 관찰', type: 'textarea', placeholder: '형태와 단면에서 확인한 특징, 기공의 균일성을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 2,
    code: '02',
    title: '바다결 버터쿠키',
    moduleGroup: '모듈 1 · 클래식 구움과자 & 전통 퓨전',
    icon: '🌊',
    themeColor: 'blue',
    accentHex: '#0284c7',
    accentDarkHex: '#0369a1',
    softHex: '#f0f9ff',
    brief: '버터의 가소성과 크림화 정도가 반죽 퍼짐·결·무늬 유지에 미친 영향을 확인합니다.',
    goal: '버터 상태와 혼합 정도를 조절하여 결이 고르고 모양이 일정한 바다결 버터쿠키를 만든다.',
    photoGuide: '쿠키 전체 배열과 무늬가 보이는 윗면 사진, 두께와 조직이 보이는 단면 사진을 권장합니다.',
    keyQuestions: ['크림화 정도가 오븐 속 퍼짐에 미친 영향은?', '버터 온도가 결 형성에 미친 차이는?'],
    standardSteps: [
      '1. 실온 버터(18~20℃)를 볼에 넣고 거품기로 부드럽게 마요네즈 상태로 푼다.',
      '2. 슈거파우더와 소금을 넣고 색이 뽀얗게 밝아질 때까지 가볍게 크림화한다.',
      '3. 실온 달걀을 2~3회 나누어 넣으며 기름 분리 없이 완벽하게 유화시킨다.',
      '4. 체 친 박력분을 넣고 고무주걱 날로 자르듯이 섞어 글루텐 형성을 차단한다.',
      '5. 별깍지를 끼운 짤주머니에 반죽을 담고 테프론 시트 위에 바다 물결 무늬로 균일하게 짠다.',
      '6. 170℃ 오븐에서 13~15분간 테두리가 연한 황금빛이 돌 때까지 굽는다.',
    ],
    flapTitle: '🧈 버터 가소성(Plasticity) & 크림화 판정 플랩',
    flapHint: '버터 상태에 따른 결 형성을 확인하세요',
    flapContent: {
      secretTip: '작업 전 버터는 손가락이 부드럽게 들어가는 18~20℃ 포마드 상태여야 합니다. 너무 녹으면 쿠키 무늬가 오븐에서 녹아내립니다.',
      sciencePrinciple: '설탕 결정이 버터 속에 공기 방울을 포집하면서 크림화됩니다. 지나치면 오븐 속에서 쿠키가 주저앉고, 부족하면 딱딱해집니다.',
      goldenRule: '가루 재료를 넣은 후에는 절대로 치대지 말고 주걱 날로 자르듯이 섞어 글루텐 형성을 차단하세요.',
    },
    fields: [
      { key: 'formula', label: '표준 배합과 실제 계량', type: 'textarea', placeholder: '버터·설탕·달걀·가루의 실제 계량값', fullWidth: true },
      { key: 'butterTemp', label: '작업 전 버터온도(℃)', type: 'number', placeholder: '예: 20', unitSuffix: '℃' },
      { key: 'creaming', label: '크림화 상태', type: 'select', options: ['부족', '적정', '과다'] },
      { key: 'doughTemp', label: '완성 반죽온도(℃)', type: 'number', placeholder: '예: 22', unitSuffix: '℃' },
      { key: 'bakeCondition', label: '굽기조건', type: 'text', placeholder: '예: 170℃ / 14분' },
      { key: 'quality', label: '퍼짐·무늬·바삭함 관찰', type: 'textarea', placeholder: '크기 편차와 무늬 유지 상태, 식감을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 3,
    code: '03',
    title: '광안대교 사블레',
    moduleGroup: '모듈 1 · 클래식 구움과자 & 전통 퓨전',
    icon: '🌉',
    themeColor: 'indigo',
    accentHex: '#4f46e5',
    accentDarkHex: '#4338ca',
    softHex: '#eef2ff',
    brief: '사블레의 최소 혼합·냉장 휴지·균일한 두께가 광안대교 형태 유지에 미친 영향을 기록합니다.',
    goal: '과혼합을 피하고 반죽 두께를 일정하게 정형하여 선명한 광안대교 사블레를 완성한다.',
    photoGuide: '광안대교 선이 잘 보이는 윗면과 쿠키 두께를 비교할 수 있는 옆면 사진을 권장합니다.',
    keyQuestions: ['글루텐 형성 억제를 위한 혼합 포인트는?', '휴지 후 밀어펴기 두께의 균일성은?'],
    standardSteps: [
      '1. 깍둑썰기한 차가운 버터와 체 친 박력분, 아몬드가루를 손바닥으로 비벼 보슬보슬한 모래알(Sablage)로 만든다.',
      '2. 슈거파우더와 달걀노른자를 넣고 스크래퍼로 가볍게 자르며 한 덩어리로 뭉친다 (절대 치대지 않음).',
      '3. 반죽을 납작하게 눌러 랩에 감싼 후 냉장고에서 최소 40분 이상 단단하게 휴지시킨다.',
      '4. 작업대에 덧가루를 살짝 뿌리고 5mm 두께 각봉을 대어 밀대로 평평하고 균일하게 민다.',
      '5. 광안대교 모양 커터로 찍어내고 오븐 팬에 간격을 두고 팬닝한다 (팬닝 후 냉동 5분 권장).',
      '6. 165℃ 예열 오븐에서 14~16분간 구워 수축 없이 선명한 브릿지 라인을 완성한다.',
    ],
    flapTitle: '🌉 모래처럼 바스러지는 사블라주(Sablage) 기법',
    flapHint: '모양 변형 없는 정밀 커팅 팁',
    flapContent: {
      secretTip: '차가운 버터 조각을 가루와 함께 손바닥으로 비벼 모래알 상태로 만드는 사블라주를 거치면 지방막이 밀가루 단백질을 코팅해 바삭함이 극대화됩니다.',
      sciencePrinciple: '반죽 휴지는 팽창된 글루텐 탄성을 진정시키고 수분을 균등 분산시켜, 구울 때 광안대교 커터 라인이 일그러지지 않게 돕습니다.',
      goldenRule: '밀어 펼 때 5mm 각봉을 양옆에 대고 롤러로 밀어 편차 없는 두께를 유지하세요.',
    },
    fields: [
      { key: 'formula', label: '표준 배합과 실제 계량', type: 'textarea', placeholder: '재료별 계량값과 변경사항', fullWidth: true },
      { key: 'mixState', label: '혼합 종료 판단', type: 'text', placeholder: '예: 가루가 막 보이지 않는 상태' },
      { key: 'restTime', label: '냉장 휴지시간(분)', type: 'number', placeholder: '예: 40', unitSuffix: '분' },
      { key: 'thickness', label: '밀어 편 반죽 두께(mm)', type: 'number', placeholder: '예: 5', unitSuffix: 'mm' },
      { key: 'bakeCondition', label: '굽기조건', type: 'text', placeholder: '예: 165℃ / 15분' },
      { key: 'quality', label: '수축·퍼짐·선명도 관찰', type: 'textarea', placeholder: '광안대교 형태가 정밀하게 유지되었는지 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 4,
    code: '04',
    title: '부산 갈매기 앙금 떡케이크',
    moduleGroup: '모듈 1 · 클래식 구움과자 & 전통 퓨전',
    icon: '🕊️',
    themeColor: 'cyan',
    accentHex: '#0891b2',
    accentDarkHex: '#0e7490',
    softHex: '#ecfeff',
    brief: '설기떡의 수분·찜 상태와 앙금의 되기·조색·짜기 압력이 부산 갈매기와 바다 장식 표현에 미친 영향을 기록합니다.',
    goal: '설기떡 시트의 수분과 익힘을 관리하고, 바다색 앙금과 갈매기 장식을 조화롭게 구성하여 부산 상징 떡케이크를 완성한다.',
    photoGuide: '떡케이크 전체의 바다색 구성과 갈매기 장식, 설기떡 단면이 보이도록 촬영하세요.',
    keyQuestions: ['쌀가루 물주기의 손감촉 판정과 익힘 정도는?', '앙금 플라워/파도 짜기 시 압력 조절은?'],
    standardSteps: [
      '1. 습식 멥쌀가루에 물을 고루 주어 양손으로 비빈 후 주먹으로 쥐어 뭉침성을 확인한다.',
      '2. 중간체에 2회 곱게 내린 뒤 찌기 직전에 설탕을 넣고 가볍게 섞는다.',
      '3. 실리콘 시루밑을 깐 찜기에 무스링을 올리고 쌀가루를 안친 뒤 스크래퍼로 윗면을 평평하게 정리한다.',
      '4. 김 오른 물솥에 올려 강불에서 20분간 찌고 불을 끈 후 5분간 뜸을 들인다.',
      '5. 백앙금에 생크림을 소량 섞어 부드럽게 농도를 맞추고 천연 색소로 바다색과 백색을 조색한다.',
      '6. 한 김 식힌 설기 시트 위에 파도 그러데이션과 부산 갈매기 장식을 섬세하게 파이핑한다.',
    ],
    flapTitle: '🕊️ 쌀가루 주먹쥐기 판정과 앙금 45도 파이핑',
    flapHint: '촉촉한 백설기와 섬세한 갈매기 조색 비법',
    flapContent: {
      secretTip: '쌀가루에 물을 준 후 한 주먹 꽉 쥐어 가볍게 위로 튕겼을 때 부서지지 않고 손가락으로 툭 치면 쪼개지는 상태가 완벽한 수분율입니다.',
      sciencePrinciple: '스팀으로 찌는 동안 전분이 충분히 호화(Gelatinization)되어 쫄깃함을 유지하고, 뜸들이기(5분)가 떡의 균일한 촉촉함을 완성합니다.',
      goldenRule: '앙금 크림이 너무 단단하면 생크림이나 우유를 티스푼 단위로 섞어 손목에 무리 없는 점도를 맞추세요.',
    },
    fields: [
      { key: 'formula', label: '설기떡·앙금 실제 배합', type: 'textarea', placeholder: '쌀가루·물·설탕·앙금·천연색소 사용량', fullWidth: true },
      { key: 'moisture', label: '쌀가루 수분 맞추기', type: 'text', placeholder: '물 주기 양과 손으로 쥐었을 때 뭉침 상태' },
      { key: 'steam', label: '찌기·뜸들이기 조건', type: 'text', placeholder: '예: 찜 20분 / 뜸 5분' },
      { key: 'beanPaste', label: '앙금 되기와 조색', type: 'select', options: ['묽음', '적정', '단단함', '색이 고르지 않음'] },
      { key: 'piping', label: '갈매기·파도 짜기 상태', type: 'textarea', placeholder: '깍지 번호, 손목 각도 및 짜기 압력 제어', fullWidth: true },
      { key: 'quality', label: '떡 식감·균열·장식 균형', type: 'textarea', placeholder: '단면 수분감, 노화 속도, 장식 조화를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 5,
    code: '05',
    title: '해운대 제누아즈',
    moduleGroup: '모듈 2 · 케이크 & 슈 페이스트리',
    icon: '🍰',
    themeColor: 'amber',
    accentHex: '#d97706',
    accentDarkHex: '#b45309',
    softHex: '#fffbeb',
    brief: '전란 거품의 리본 상태·비중·폴딩이 제누아즈의 높이와 기공에, 샹티이 휘핑 상태가 해운대 파도 장식에 미친 영향을 확인합니다.',
    goal: '기포 손실을 줄여 균일한 제누아즈를 굽고 샹티이로 해운대 바다의 파도 이미지를 표현한다.',
    photoGuide: '해운대 제누아즈의 전체 높이와 중앙 단면, 샹티이 파도 장식이 함께 보이도록 촬영하세요.',
    keyQuestions: ['비중 측정을 통한 반죽 기포 안정성은?', '샹티이 크림의 동물성 유지방 비율과 오버휘핑 주의점은?'],
    standardSteps: [
      '1. 전란에 설탕과 물엿을 넣고 40℃ 따뜻한 물에 중탕하여 설탕을 완전히 녹인다.',
      '2. 핸드믹서 고속으로 휘핑하여 반죽을 떨어뜨렸을 때 자국이 3초간 유지되는 리본 상태를 만든다.',
      '3. 저속으로 1~2분간 돌려 큰 거품을 정리하고 균일한 미세 기포를 형성한다 (기포 정리).',
      '4. 체 친 박력분을 2회 나누어 넣고 고무주걱으로 아래에서 위로 퍼올리듯 빠르게 폴딩한다.',
      '5. 55℃ 녹인 버터와 우유에 반죽 일부를 덜어 섞은 후 본 반죽에 넣고 비중(0.45~0.50)을 맞춘다.',
      '6. 유산지를 깐 원형 틀에 팬닝하고 175℃ 오븐에서 28~30분간 구워 충격을 준 뒤 식힌다.',
    ],
    flapTitle: '🌊 제누아즈의 생명선: 비중(0.45~0.50) 계산법',
    flapHint: '꺼지지 않는 스펀지 케이크의 황금 공식',
    flapContent: {
      secretTip: '전란에 설탕을 넣고 40℃로 중탕 데운 뒤 고속 휘핑하면 거품의 표면장력이 약해져 훨씬 조밀하고 단단한 리본 스테이지를 만듭니다.',
      sciencePrinciple: '비중 공식 = (반죽 무게) ÷ (같은 컵의 물 무게). 비중이 0.40 이하면 너무 가벼워 떡지고, 0.55 이상이면 무거워 부풀지 않습니다.',
      goldenRule: '녹인 버터(55℃)를 넣을 때는 주걱에 흘려 담고 반죽 일부를 덜어 희생 반죽을 만든 뒤 섞으세요.',
    },
    fields: [
      { key: 'formula', label: '제누아즈·샹티이 실제 배합', type: 'textarea', placeholder: '전란·설탕·박력분·버터·생크림 계량값', fullWidth: true },
      { key: 'eggTemp', label: '휘핑 전 달걀온도(℃)', type: 'number', placeholder: '예: 38 (중탕 후 온도)', unitSuffix: '℃' },
      { key: 'specificGravity', label: '반죽 비중', type: 'number', placeholder: '예: 0.48' },
      { key: 'folding', label: '가루 혼합(폴딩) 상태', type: 'select', options: ['부족(날가루)', '적정(윤기)', '과다(기포꺼짐)'] },
      { key: 'bakeCondition', label: '굽기조건', type: 'text', placeholder: '예: 175℃ / 28분' },
      { key: 'quality', label: '높이·단면 기공·샹티이 장식', type: 'textarea', placeholder: '부피감, 기공의 균일도, 크림의 텍스처와 파도 표현을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 6,
    code: '06',
    title: '태종대 에클레어 슈',
    moduleGroup: '모듈 2 · 케이크 & 슈 페이스트리',
    icon: '🥐',
    themeColor: 'orange',
    accentHex: '#ea580c',
    accentDarkHex: '#c2410c',
    softHex: '#fff7ed',
    brief: '슈 반죽의 호화·달걀 투입량·굽기 중 팽창과 크렘 파티시에르의 농도를 연결하여 태종대 절벽처럼 견고한 형태를 완성합니다.',
    goal: '슈 반죽 호화 농도와 크렘 파티시에르의 되기를 판정하여 속이 비고 껍질과 필링이 안정적인 태종대 에클레어를 만든다.',
    photoGuide: '에클레어의 길이와 균일성, 내부 공동과 크림 충전 상태가 보이는 단면 사진을 권장합니다.',
    keyQuestions: ['호화 반죽 냄비 바닥 피막 형성과 호화 온도는?', '오븐 문 열지 않고 수증기 팽창 유지 방법은?'],
    standardSteps: [
      '1. 냄비에 물, 우유, 버터 조각, 소금, 설탕을 넣고 센불에서 버터가 녹아 팔팔 끓어오르게 한다.',
      '2. 불을 끄고 체 친 박력분을 한 번에 넣은 뒤 주걱으로 날가루가 없을 때까지 빠르게 섞는다.',
      '3. 다시 약불에 올려 1~2분간 볶으며 냄비 바닥에 하얀 막(피막)이 생길 때까지 충분히 호화(Panade)시킨다.',
      '4. 반죽을 볼에 옮겨 60℃ 이하로 한 김 식힌 뒤, 푼 달걀을 조금씩 넣어가며 주걱 끝에 역삼각형 모양이 유지되는 농도를 맞춘다.',
      '5. 1cm 원형 또는 톱니 깍지를 끼우고 철판에 12cm 길이(28g)로 일정하게 파이핑한다.',
      '6. 200℃에서 15분간 부풀린 후, 170℃로 낮춰 20분간 바삭하게 구워낸다 (초기 문 열림 금지).',
    ],
    flapTitle: '🥐 전분 호화 80℃ 피막과 2단계 오븐 온도',
    flapHint: '속이 텅 빈 바삭한 에클레어 껍질의 과학',
    flapContent: {
      secretTip: '냄비 바닥에 하얀 피막이 얇게 생길 때까지(반죽온도 약 75~80℃) 충분히 볶아야 밀가루 전분이 완벽히 호화되어 수분을 흡수합니다.',
      sciencePrinciple: '계란을 넣은 뒤 주걱을 들었을 때 역삼각형 모양으로 3~4초 머물다 뚝 떨어지는 농도가 완벽한 반죽입니다.',
      goldenRule: '굽기 초기 15분간은 수증기 압력으로 껍질이 형성되는 단계이므로 절대로 오븐 문을 열지 마세요!',
    },
    fields: [
      { key: 'formula', label: '슈·크렘 파티시에르 배합', type: 'textarea', placeholder: '물·우유·버터·박력분·달걀·커스터드 재료량', fullWidth: true },
      { key: 'panade', label: '호화 반죽(파나드) 상태', type: 'text', placeholder: '예: 바닥 얇은 막 형성 및 75~80℃ 도달' },
      { key: 'eggAmount', label: '실제 달걀 투입량(g)', type: 'number', placeholder: '예: 180', unitSuffix: 'g' },
      { key: 'piping', label: '팬닝 길이·중량', type: 'text', placeholder: '예: 12cm / 28g' },
      { key: 'bakeCondition', label: '단계별 굽기조건', type: 'text', placeholder: '예: 200℃ 15분 → 170℃ 20분' },
      { key: 'quality', label: '팽창·내부 공동·크림 농도', type: 'textarea', placeholder: '슈 껍질의 바삭함과 크림의 찰기, 단면 충전률을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 7,
    code: '07',
    title: '대저 토마토 타르트',
    moduleGroup: '모듈 2 · 케이크 & 슈 페이스트리',
    icon: '🍅',
    themeColor: 'rose',
    accentHex: '#e11d48',
    accentDarkHex: '#be123c',
    softHex: '#fff1f2',
    brief: '대저 짭짤이 토마토의 수분 처리와 타르트 반죽의 휴지·블라인드 베이킹을 중심으로 기록합니다.',
    goal: '대저 토마토의 수분을 조절하고 바삭한 타르트 파트 사블레와 균형 있는 아파레유를 완성한다.',
    photoGuide: '타르트 전체와 옆면, 필링과 바닥 바삭함이 보이는 단면 사진을 권장합니다.',
    keyQuestions: ['생과일 수분 침투를 막기 위한 누름돌 베이킹과 바닥 코팅은?', '단맛·산미·감칠맛 밸런스는?'],
    standardSteps: [
      '1. 파트 사블레 반죽을 타르트 링에 퐁사주(밀착)하고 포크로 피케(구멍)한 뒤 냉장 휴지한다.',
      '2. 종이호일과 누름돌을 올리고 170℃에서 15분간 초벌(블라인드) 베이킹한다.',
      '3. 누름돌을 빼고 달걀물을 바른 뒤 3분간 추가로 구워 바닥 방수 코팅막을 형성한다.',
      '4. 대저 짭짤이 토마토를 슬라이스해 소금을 살짝 뿌려 삼투압으로 수분을 제거한다.',
      '5. 타르트 쉘에 아몬드 크림 또는 치즈 아파레유를 채우고 건조된 토마토를 정렬한다.',
      '6. 165℃ 오븐에서 20분간 구워 바삭한 타르트지와 감칠맛 도는 토마토 타르트를 완성한다.',
    ],
    flapTitle: '🍅 삼투 탈수와 블라인드 베이킹 누름돌 분리 타이밍',
    flapHint: '바닥이 눅눅해지지 않는 파삭한 타르트지 비법',
    flapContent: {
      secretTip: '대저 토마토를 얇게 슬라이스해 소금을 살짝 뿌려 키친타월에 20분간 올려두면 수분은 빠지고 본연의 단맛과 감칠맛이 응축됩니다.',
      sciencePrinciple: '타르트 바닥에 포크로 피케(Piquer) 구멍을 내고 누름돌을 올려 170℃에서 15분간 초벌 굽기한 뒤, 계란물을 얇게 발라 3분 더 구우면 완벽한 방수 코팅막이 형성됩니다.',
      goldenRule: '필링을 채우기 전에 타르트 쉘이 완전히 식었는지 확인하세요. 열기가 남아있으면 버터가 녹아내립니다.',
    },
    fields: [
      { key: 'formula', label: '타르트지·필링 배합', type: 'textarea', placeholder: '파트 사블레와 토마토 아파레유 배합비', fullWidth: true },
      { key: 'tomatoPrep', label: '토마토 전처리', type: 'text', placeholder: '절단 두께, 소금 탈수, 오븐 저온 건조 상태' },
      { key: 'restTime', label: '반죽 휴지시간(분)', type: 'number', placeholder: '예: 40', unitSuffix: '분' },
      { key: 'blindBake', label: '블라인드 베이킹(누름돌)', type: 'text', placeholder: '예: 170℃ / 15분' },
      { key: 'finalBake', label: '최종 굽기조건', type: 'text', placeholder: '예: 165℃ / 20분' },
      { key: 'quality', label: '바닥 눅눅함·산미·수분 관찰', type: 'textarea', placeholder: '타르트지의 파삭함과 필링의 굳기 상태를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 8,
    code: '08',
    title: '기장 다시마 솔티드 캐러멜',
    moduleGroup: '모듈 2 · 케이크 & 슈 페이스트리',
    icon: '🌿',
    themeColor: 'emerald',
    accentHex: '#059669',
    accentDarkHex: '#047857',
    softHex: '#ecfdf5',
    brief: '설탕의 캐러멜화 온도와 다시마·소금 투입 시점이 색·점도·결정화에 미친 영향을 확인합니다.',
    goal: '캐러멜의 최종 온도와 유화를 조절하여 단맛·짠맛·감칠맛이 균형 잡힌 솔티드 캐러멜을 만든다.',
    photoGuide: '캐러멜의 색과 흐름성이 보이도록 스푼 또는 단면과 함께 촬영하세요.',
    keyQuestions: ['캐러멜화 시 주걱 젓지 않는 이유와 재결정화 방지법은?', '버터와 생크림 유화 온도는?'],
    standardSteps: [
      '1. 냄비에 생크림과 기장 다시마를 넣고 70℃까지 약불로 데운 후 15분간 우려내어 체에 거른다.',
      '2. 바닥이 두꺼운 다른 냄비에 설탕과 물엿을 넣고 중불에서 젓지 않고 녹인다 (결정화 방지).',
      '3. 설탕 시럽이 깊은 호박색(170~172℃)에 도달하면 불을 끈다.',
      '4. 데워둔 따뜻한 다시마 생크림을 3~4회 나누어 부으며 거품기로 재빨리 섞어 유화한다.',
      '5. 온도가 45℃로 내려가면 버터 조각과 천일염을 넣고 핸드블렌더로 매끄럽게 유화한다.',
      '6. 테프론 시트를 깐 틀에 부어 실온에서 서서히 굳힌 후 먹기 좋은 크기로 재단한다.',
    ],
    flapTitle: '🌿 170℃ 캐러멜화 & 재결정화 방지의 황금법칙',
    flapHint: '타지 않고 부드러운 고급 캐러멜의 온도 관리',
    flapContent: {
      secretTip: '설탕을 녹일 때는 절대 주걱으로 젓지 말고 냄비 손잡이를 가볍게 돌려야 설탕 결정이 굳어 굳는 재결정화(Recrystallization)를 막을 수 있습니다.',
      sciencePrinciple: '설탕이 160~175℃에 도달하면 열분해로 풍부한 호박색과 견과류 향이 생깁니다. 이때 70℃로 데운 생크림을 넣어야 비산 폭발 없이 유화됩니다.',
      goldenRule: '기장 다시마는 생크림에 저온으로 15분간 우려내어 떫은맛 없이 은은한 바다 감칠맛(Glutamic acid)만 추출하세요.',
    },
    fields: [
      { key: 'formula', label: '표준 배합과 실제 계량', type: 'textarea', placeholder: '설탕·물엿·생크림·버터·기장다시마·천일염 계량값', fullWidth: true },
      { key: 'caramelTemp', label: '캐러멜 최종온도(℃)', type: 'number', placeholder: '예: 172', unitSuffix: '℃' },
      { key: 'creamTemp', label: '생크림 투입온도(℃)', type: 'number', placeholder: '예: 70 (온도차로 인한 비산 방지)', unitSuffix: '℃' },
      { key: 'kelpTime', label: '다시마 투입·우림시간', type: 'text', placeholder: '예: 생크림에 저온 15분 우림' },
      { key: 'texture', label: '냉각 후 점도', type: 'select', options: ['묽음', '적정(스프레드/소프트)', '단단함', '설탕결정화'] },
      { key: 'quality', label: '색·쓴맛·분리·감칠맛', type: 'textarea', placeholder: '호박색의 깊이, 뒷맛의 감칠맛, 기름 분리 여부를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 9,
    code: '09',
    title: '영도 조내기 고구마 몽블랑',
    moduleGroup: '모듈 3 · 쇼콜라 & 특화 디저트',
    icon: '🍠',
    themeColor: 'purple',
    accentHex: '#9333ea',
    accentDarkHex: '#7e22ce',
    softHex: '#faf5ff',
    brief: '고구마의 수분과 입자 크기, 샹티이와의 비율이 몽블랑 크림의 짜기성과 형태 유지에 미친 영향을 기록합니다.',
    goal: '조내기 고구마의 수분을 조절해 매끄럽고 안정적인 몽블랑 국수 크림을 완성한다.',
    photoGuide: '몽블랑 짜기 선과 전체 높이, 머랭·크림층이 보이는 단면 사진을 권장합니다.',
    keyQuestions: ['체내리기 작업의 횟수와 크림 노즐 막힘의 관계는?', '하부 머랭 베이스의 방습 처리는?'],
    standardSteps: [
      '1. 고구마를 껍질째 오븐에 구워 당도를 농축한 후 뜨거울 때 껍질을 벗겨 으깬다.',
      '2. 따뜻한 고구마에 버터와 설탕을 넣고 섞은 후 고운 체에 2회 내려 극도로 매끄러운 퓌레를 만든다.',
      '3. 생크림과 럼주를 소량씩 섞어 몽블랑 다공 깍지에서 끊김 없이 흘러나오는 농도를 조절한다.',
      '4. 구워둔 바삭한 머랭 베이스 윗면에 화이트 초콜릿을 얇게 발라 수분 차단막을 만든다.',
      '5. 머랭 위에 단단한 샹티이 크림을 돔 형태로 올리고 냉장고에서 10분간 형태를 굳힌다.',
      '6. 몽블랑 전용 노즐로 고구마 크림을 아래에서 위로 실타래처럼 촘촘히 둘러 완성한다.',
    ],
    flapTitle: '🍠 몽블랑 다공 깍지 통과를 위한 2회 미세 체내리기',
    flapHint: '끊김 없이 쏟아지는 국수 크림의 유화 팁',
    flapContent: {
      secretTip: '고구마 퓌레는 반드시 따뜻할 때 버터를 넣고 체에 최소 2회 내려 섬유질을 걸러내야 다공 노즐이 막히지 않고 매끄럽게 토출됩니다.',
      sciencePrinciple: '고구마 크림 온도가 10℃ 이하로 너무 차가우면 버터가 굳어 끊어지고, 20℃ 이상이면 녹아 돔 형태가 무너집니다.',
      goldenRule: '바닥 머랭 베이스 윗면에 녹인 화이트 초콜릿을 얇게 코팅하면 크림 수분으로 머랭이 눅눅해지는 것을 막을 수 있습니다.',
    },
    fields: [
      { key: 'formula', label: '고구마 크림·샹티이 배합', type: 'textarea', placeholder: '고구마 퓌레, 버터, 럼, 생크림 배합비', fullWidth: true },
      { key: 'sweetPotato', label: '고구마 전처리 상태', type: 'text', placeholder: '군고구마 오븐 베이킹 시간 및 체내리기 횟수' },
      { key: 'moisture', label: '수분 조절 재료와 양', type: 'text', placeholder: '예: 가당 생크림 40g 추가 혼합' },
      { key: 'creamTemp', label: '짜기 전 크림온도(℃)', type: 'number', placeholder: '예: 8', unitSuffix: '℃' },
      { key: 'piping', label: '짜기성·형태 유지', type: 'select', options: ['너무 묽음(선무너짐)', '적정(선명한 가닥)', '너무 단단함(끊김)'] },
      { key: 'quality', label: '입자감·단맛·높이 관찰', type: 'textarea', placeholder: '입자 걸림 없는 부드러움과 돔 형태 유지력을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 10,
    code: '10',
    title: '씨앗호떡 프랄리네',
    moduleGroup: '모듈 3 · 쇼콜라 & 특화 디저트',
    icon: '🌰',
    themeColor: 'amber',
    accentHex: '#b45309',
    accentDarkHex: '#92400e',
    softHex: '#fffbeb',
    brief: '견과류 캐러멜화·분쇄 정도·초콜릿 유화가 프랄리네의 향과 질감에 미친 영향을 분석합니다.',
    goal: '해바라기씨·호박씨 로스팅·분쇄·유화를 조절하여 부산 씨앗호떡을 현대적으로 재해석한 프랄리네를 만든다.',
    photoGuide: '프랄리네의 절단면과 필링 농도, 씨앗 분포가 보이도록 촬영하세요.',
    keyQuestions: ['견과류 로스팅 시 마이야르 반응의 최대 발현점은?', '분쇄 시 오일 배출과 페이스트 입자 크기는?'],
    standardSteps: [
      '1. 해바라기씨, 호박씨, 땅콩을 150℃ 오븐에서 12분간 천천히 로스팅하여 고소한 향을 올린다.',
      '2. 팬에 설탕과 물을 넣고 170℃까지 끓여 갈색 캐러멜을 만든 후 로스팅한 씨앗을 넣고 빠르게 버무린다.',
      '3. 테프론 시트에 넓게 펼쳐 완전히 식힌 후 단단한 누가를 손으로 조각낸다.',
      '4. 푸드프로세서에 넣고 펄스 모드로 갈아 원하는 식감(크런치 알갱이 or 부드러운 페이스트)을 만든다.',
      '5. 시나몬 파우더와 템퍼링한 밀크 초콜릿을 섞어 부드럽게 유화시킨다.',
      '6. 프레임에 부어 굳힌 후 한 입 크기로 절단하여 완성한다.',
    ],
    flapTitle: '🌰 견과류 마이야르 로스팅 & 페이스트 오일 분리 통제',
    flapHint: '고소한 호떡의 풍미를 담은 크런치 프랄리네 비법',
    flapContent: {
      secretTip: '씨앗과 견과는 150℃ 저온 오븐에서 12분간 천천히 구워 중심부까지 균일하게 로스팅해야 쓴맛 없이 고소한 유지방 향미가 극대화됩니다.',
      sciencePrinciple: '캐러멜 코팅된 견과류를 푸드프로세서에 갈 때 모터 열로 온도가 올라가면 기름이 겉돌므로, 펄스(Pulse) 모드로 끊어가며 갈아야 합니다.',
      goldenRule: '계피(시나몬) 가루는 0.3% 소량만 넣어 씨앗의 고소함을 가리지 않도록 밸런스를 맞추세요.',
    },
    fields: [
      { key: 'formula', label: '씨앗·견과·캐러멜 배합', type: 'textarea', placeholder: '해바라기씨, 호박씨, 땅콩, 설탕, 시나몬 비율', fullWidth: true },
      { key: 'roasting', label: '로스팅 조건', type: 'text', placeholder: '예: 150℃ / 12분' },
      { key: 'caramelTemp', label: '캐러멜 최종온도(℃)', type: 'number', placeholder: '예: 170', unitSuffix: '℃' },
      { key: 'grind', label: '분쇄 상태', type: 'select', options: ['거침(크런치)', '적정(부드러운 페이스트)', '과다분쇄(오일과다분리)'] },
      { key: 'emulsion', label: '유화 상태', type: 'select', options: ['분리', '적정', '과도하게 단단함'] },
      { key: 'quality', label: '고소함·입자·흐름성', type: 'textarea', placeholder: '시나몬 향과 고소한 맛의 밸런스, 식감을 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 11,
    code: '11',
    title: '카멜리아 봉봉 쇼콜라',
    moduleGroup: '모듈 3 · 쇼콜라 & 특화 디저트',
    icon: '🍫',
    themeColor: 'stone',
    accentHex: '#78350f',
    accentDarkHex: '#451a03',
    softHex: '#fafaf9',
    brief: '초콜릿 템퍼링과 가나슈 유화·결정화가 광택·수축·식감에 미친 영향을 확인합니다.',
    goal: '초콜릿 템퍼링 온도곡선과 가나슈 상태를 관리하여 광택과 스냅이 좋은 카멜리아 몰드 초콜릿을 완성한다.',
    photoGuide: '몰드에서 깔끔하게 분리된 전체 모습과 얇은 쉘 두께·가나슈가 보이는 단면을 촬영하세요.',
    keyQuestions: ['카카오버터 베타(V)형 결정 형성을 위한 온도 조절은?', '쉘 두께의 균일성을 만드는 탭핑 테크닉은?'],
    standardSteps: [
      '1. 초콜릿 전용 몰드를 알코올과 탈지면으로 깨끗이 닦아 지문과 유분기를 제거한다.',
      '2. 다크 초콜릿을 45~50℃로 완전 용해 후, 27~28℃로 냉각하고 다시 31~32℃로 올려 템퍼링한다.',
      '3. 몰드에 템퍼링된 초콜릿을 가득 채우고 기포를 탭핑한 뒤 뒤집어 2mm 두께의 얇은 쉘을 남기고 쏟아낸다.',
      '4. 스크래퍼로 윗면을 긁어 정리하고 서늘한 곳(18℃)에서 쉘을 완전히 굳힌다.',
      '5. 동백꽃 향 가나슈를 28℃로 식힌 후 짤주머니로 몰드의 80% 높이까지 채운다.',
      '6. 템퍼링된 초콜릿으로 뚜껑(바닥)을 덮고 굳힌 후 몰드를 가볍게 비틀어 영롱한 광택의 봉봉을 분리한다.',
    ],
    flapTitle: '🍫 카카오버터 베타(V)형 결정 템퍼링 온도 곡선',
    flapHint: '빛나는 광택과 경쾌한 스냅(Snap)의 비밀',
    flapContent: {
      secretTip: '다크 초콜릿 기준: 45~50℃ 완전 용해 → 27~28℃ 불안정 결정 생성 → 31~32℃ 안정 베타(V) 결정만 남기는 3단계 온도 곡선을 0.5℃ 오차 이내로 준수하세요.',
      sciencePrinciple: '템퍼링이 완벽하면 카카오버터가 굳으면서 수축해 몰드에서 손대지 않아도 쏙 빠져나오며, 매끄러운 광택을 띱니다.',
      goldenRule: '가나슈 필링을 채울 때는 28~30℃ 온도로 식힌 후 채워야 얇은 초콜릿 쉘이 녹지 않습니다.',
    },
    fields: [
      { key: 'formula', label: '쉘·가나슈 배합', type: 'textarea', placeholder: '다크/밀크 초콜릿 및 동백꽃 향 가나슈 필링 배합', fullWidth: true },
      { key: 'meltTemp', label: '용해 최고온도(℃)', type: 'number', placeholder: '예: 45~50', unitSuffix: '℃' },
      { key: 'coolTemp', label: '냉각 최저온도(℃)', type: 'number', placeholder: '예: 27~28', unitSuffix: '℃' },
      { key: 'workTemp', label: '작업 적정온도(℃)', type: 'number', placeholder: '예: 31~32', unitSuffix: '℃' },
      { key: 'ganache', label: '가나슈 유화 상태', type: 'select', options: ['기름분리', '매끄러운 에멀전(적정)', '기포혼입'] },
      { key: 'quality', label: '광택·수축·스냅·쉘 두께', type: 'textarea', placeholder: '몰드 이형성, 쉘 두께의 얇은 정도(2mm 이내), 씹었을 때의 소리를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 12,
    code: '12',
    title: '감천 레인보우 롤케이크',
    moduleGroup: '모듈 3 · 쇼콜라 & 특화 디저트',
    icon: '🌈',
    themeColor: 'pink',
    accentHex: '#db2777',
    accentDarkHex: '#be185d',
    softHex: '#fdf2f8',
    brief: '시트의 머랭 안정성·색 반죽 분할·말기 온도가 롤의 무늬와 균열에 미친 영향을 기록합니다.',
    goal: '감천문화마을의 파스텔톤 색을 균일하게 표현하고 시트 터짐 없이 레인보우 롤케이크를 말아낸다.',
    photoGuide: '색 배열이 보이는 전체 롤과 나선 원형·크림 균형이 보이는 단면을 촬영하세요.',
    keyQuestions: ['색소 혼합 시 기포 사멸을 막는 폴딩법은?', '말기 시트의 수분 유지와 최적 온도(30~35℃)는?'],
    standardSteps: [
      '1. 흰자에 설탕을 3회 나누어 넣으며 뿔이 살짝 휘는 부드럽고 윤기 나는 머랭(80%)을 올린다.',
      '2. 노른자와 가루를 섞은 기본 비스퀴 반죽을 5개 볼에 동일한 무게(각 120g)로 정밀 분할한다.',
      '3. 감천마을의 파스텔 색소를 각각 넣어 기포가 꺼지지 않게 주걱 날로 재빨리 폴딩한다.',
      '4. 짤주머니에 색별로 담아 유산지 팬 위에 사선 또는 평행 줄무늬로 빈틈없이 균일하게 짠다.',
      '5. 180℃ 예열 오븐에서 11~12분간 구운 후 즉시 팬에서 분리하여 수분이 날아가지 않게 덮어둔다.',
      '6. 시트가 32℃ 미온수 온도로 식었을 때 마스카포네 샹티이 크림을 펴 바르고 유산지를 들어 균열 없이 말아 냉장 굳힌다.',
    ],
    flapTitle: '🌈 색 경계선 보존과 터짐 없는 32℃ 미온수 말기',
    flapHint: '갈라지지 않는 부드러운 롤 시트의 수분 제어',
    flapContent: {
      secretTip: '각 색깔 반죽은 짤주머니에 담아 평행하게 일정한 두께로 짜주어야 구웠을 때 색이 서로 번지거나 울퉁불퉁해지지 않습니다.',
      sciencePrinciple: '시트가 완전히 식은 상태(20℃ 이하)에서 말면 단백질 굳음으로 인해 표면이 터집니다. 30~35℃ 온기가 남아있을 때 유산지를 덮어 말아야 합니다.',
      goldenRule: '마스카포네 샹티이 크림은 단단하게(80%) 휘핑하여 말았을 때 중심 축이 무너지지 않도록 지탱하세요.',
    },
    fields: [
      { key: 'formula', label: '시트·크림 배합', type: 'textarea', placeholder: '비스퀴 시트 배합 및 마스카포네 샹티이 크림 배합', fullWidth: true },
      { key: 'colorWeight', label: '색별 반죽 분할량(g)', type: 'text', placeholder: '예: 5색 각 120g 균등 분할' },
      { key: 'bakeCondition', label: '시트 굽기조건', type: 'text', placeholder: '예: 180℃ / 11~12분' },
      { key: 'rollTemp', label: '말기 시작 시트온도(℃)', type: 'number', placeholder: '예: 32', unitSuffix: '℃' },
      { key: 'crack', label: '시트 표면 상태', type: 'select', options: ['균열 전혀 없음(매끄러움)', '미세 실금', '큰 터짐/갈라짐'] },
      { key: 'quality', label: '색 선명도·나선·기공 관찰', type: 'textarea', placeholder: '색의 경계선 번짐 유무, 크림 쏠림 여부를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 13,
    code: '13',
    title: '오륙도 무스',
    moduleGroup: '모듈 3 · 쇼콜라 & 특화 디저트',
    icon: '🏝️',
    themeColor: 'teal',
    accentHex: '#0f766e',
    accentDarkHex: '#115e59',
    softHex: '#f0fdfa',
    brief: '무스의 온도·젤라틴·휘핑크림 혼합과 냉동·해동이 층 안정성과 식감에 미친 영향을 확인합니다.',
    goal: '구성요소의 온도를 맞추고 기포 손실을 줄여 층이 선명하고 부드러운 오륙도 무스를 완성한다.',
    photoGuide: '오륙도 암초 형태가 보이는 글라사주 표면과 내부 층·인서트가 보이는 단면을 촬영하세요.',
    keyQuestions: ['무스 베이스와 생크림 혼합 시 최적 온도(30℃)는?', '글라사주 피복 시 기포 방지 온도는?'],
    standardSteps: [
      '1. 망고 인서트를 끓여 젤라틴을 섞은 후 실리콘 몰드에 부어 -18℃에서 꽁꽁 얼린다.',
      '2. 바다색 앙글레즈 무스 베이스를 30℃로 식힌 후 불린 젤라틴을 완전히 녹인다.',
      '3. 생크림을 부드러운 소프트 피크(60%)로 휘핑하여 베이스에 2회 나누어 섞는다.',
      '4. 무스 몰드에 무스 크림을 절반 채우고 냉동 인서트를 중앙에 넣은 뒤 나머지 크림과 시트로 덮어 급랭한다.',
      '5. 미러 글라사주를 끓여 핸드블렌더로 기포 없이 갈아낸 후 32℃ 작업 온도로 맞춘다.',
      '6. 냉동고에서 꺼낸 무스 케이크 위에 32℃ 글라사주를 한 번에 부어 코팅하고 암초 초콜릿 장식을 올린다.',
    ],
    flapTitle: '🏝️ 거울 같은 미러 글라사주(Miroir) 32℃ 피복 테크닉',
    flapHint: '층 분리 없는 무스와 영롱한 바다빛 연출법',
    flapContent: {
      secretTip: '판젤라틴은 찬물에서 10분간 불린 후 물기를 꽉 짜서 55℃ 안팎의 따뜻한 베이스에 녹여야 덩어리지지 않습니다.',
      sciencePrinciple: '글라사주 온도가 35℃ 이상이면 무스가 녹아내리고, 28℃ 이하이면 끈적여서 표면에 매끄럽게 흐르지 못하므로 정확히 31~33℃에 부어야 합니다.',
      goldenRule: '글라사주를 믹서로 갈 때 핸드블렌더 날을 절대 표면 위로 올리지 말고 바닥에 붙여 기포 발생을 억제하세요.',
    },
    fields: [
      { key: 'formula', label: '무스·인서트·글라사주 배합', type: 'textarea', placeholder: '바다색 블루큐라소 무스, 망고 인서트, 미루아르 글라사주', fullWidth: true },
      { key: 'baseTemp', label: '베이스 혼합온도(℃)', type: 'number', placeholder: '예: 30', unitSuffix: '℃' },
      { key: 'gelatin', label: '판젤라틴 사용량(g)', type: 'number', placeholder: '예: 6', unitSuffix: 'g' },
      { key: 'creamPeak', label: '휘핑크림 상태', type: 'select', options: ['소프트 피크(60%)', '미디엄 피크(70%)', '과휘핑(80%이상)'] },
      { key: 'freeze', label: '냉동·해동 시간', type: 'text', placeholder: '예: 급속냉동 4시간 / 쇼케이스 해동 2시간' },
      { key: 'quality', label: '층 분리·기포·글라사주 광택', type: 'textarea', placeholder: '단면 레이어의 평탄함과 글라사주의 거울 광택도를 기록하세요.', fullWidth: true },
    ],
  },
  {
    id: 14,
    code: '14',
    title: '플레이팅과 카페 디저트 구성',
    moduleGroup: '모듈 4 · 디저트 비즈니스 & 상품화',
    icon: '🍽️',
    themeColor: 'sky',
    accentHex: '#0284c7',
    accentDarkHex: '#0369a1',
    softHex: '#f0f9ff',
    brief: '맛의 흐름과 색·높이·여백·소스 배치를 함께 고려해 카페 디저트 한 접시를 구성합니다.',
    goal: '디저트와 음료의 맛·색·질감을 연결하고 부산 이야기가 보이는 플레이팅을 완성한다.',
    photoGuide: '정면 45도 각도 사진과 접시 전체 구성이 보이는 탑뷰(수직 항공샷) 사진을 각각 촬영하세요.',
    keyQuestions: ['접시 위 3가지 식감(바삭/크리미/촉촉) 배치 원리는?', '온도와 서빙 타이밍의 상호작용은?'],
    standardSteps: [
      '1. 플레이팅할 메인 디저트의 중심 테마와 부산 스토리텔링 콘셉트를 확정한다.',
      '2. 차가운 도자기 접시를 깨끗이 닦고 여백(40~50%)을 계산하여 메인 위치를 선정한다.',
      '3. 스푼 또는 드로잉 붓을 사용하여 과일 퓌레 소스를 대담하고 자연스럽게 터치한다.',
      '4. 메인 디저트가 미끄러지지 않도록 바닥에 고소한 크럼블을 소량 안착시킨다.',
      '5. 핀셋으로 식용 꽃, 허브, 튀일 가니시를 높이감(입체감)이 살아나도록 정밀 배치한다.',
      '6. 서빙 온도(디저트 6℃ / 페어링 음료)를 점검하고 3분 이내 고객에게 제공한다.',
    ],
    flapTitle: '🍽️ 접시 위 3대 텍스처(Texture)와 황금 분할 구도',
    flapHint: '미각과 시각을 사로잡는 파인 플레이팅 원리',
    flapContent: {
      secretTip: '한 접시 안에 크리미(무스/크림), 바삭(크럼블/튀일), 촉촉(시트/과일)의 3가지 대조적 식감이 반드시 공존해야 마지막 한 입까지 질리지 않습니다.',
      sciencePrinciple: '접시의 여백은 40~50%를 유지해야 시선이 분산되지 않고 메인 디저트에 집중됩니다.',
      goldenRule: '소스 드로잉은 손을 떨지 말고 한 번의 과감한 제스처로 붓질하듯 연출하세요.',
    },
    fields: [
      { key: 'menu', label: '디저트·음료 구성', type: 'textarea', placeholder: '메인 디저트, 곁들임 퓌레/소스, 크럼블, 허브, 페어링 음료', fullWidth: true },
      { key: 'concept', label: '부산 콘셉트와 스토리텔링', type: 'textarea', placeholder: '부산의 어떤 명소나 감성을 접시 위에 시각화했는지 서술', fullWidth: true },
      { key: 'tasteFlow', label: '맛의 흐름과 텍스처', type: 'text', placeholder: '예: 산뜻한 유자 산미 → 달콤한 바닐라 → 고소한 견과 크런치' },
      { key: 'composition', label: '색·높이·여백(구도) 평가', type: 'textarea', placeholder: '접시의 여백 비율, 시선의 집중점, 입체감 연출 평가', fullWidth: true },
      { key: 'serviceTemp', label: '제공 온도·서빙 제한시간', type: 'text', placeholder: '예: 디저트 6℃, 소스 온기 35℃ / 완성 후 3분 내 제공' },
      { key: 'pairing', label: '음료 페어링 근거', type: 'textarea', placeholder: '선택한 음료의 산미·바디감이 디저트의 단맛을 어떻게 정리하는지 서술', fullWidth: true },
    ],
  },
  {
    id: 15,
    code: '15',
    title: '원가계산과 표준레시피 작성',
    moduleGroup: '모듈 4 · 디저트 비즈니스 & 상품화',
    icon: '🧾',
    themeColor: 'stone',
    accentHex: '#57534e',
    accentDarkHex: '#44403c',
    softHex: '#fafaf9',
    brief: '표준레시피·수율·손실률을 근거로 재료비와 포장비를 계산하고 판매가를 판단합니다.',
    goal: '표준레시피를 작성하고 실제 원가와 수율을 계산하여 합리적인 판매가를 제안한다.',
    photoGuide: '완제품 규격 측정 장면과 포장 상태, 완성된 표준 레시피북을 함께 촬영하세요.',
    keyQuestions: ['수율과 공정 로스율의 산출 근거는?', '적정 원가율(30~35%)에 따른 목표 마진은?'],
    standardSteps: [
      '1. 1배치(Batch) 생산에 소요되는 모든 원재료의 단위당 단가와 실투입량을 기재한다.',
      '2. 제조 중 발생하는 공정 로스(반죽 볼 잔류, 굽기 감량 5~8%)를 반영하여 실수율을 산출한다.',
      '3. 상자, 개별 비닐, 방습제, 스티커 등 포장 부자재 비용을 1개당 단가로 합산한다.',
      '4. (총 재료비 + 총 포장비) ÷ 정상 생산 수량으로 1개당 제조 원가를 도출한다.',
      '5. 목표 원가율 30%를 적용하여 권장 판매가를 계산한다 (개별원가 ÷ 0.3).',
      '6. 주변 상권 및 경쟁 디저트와의 시장 가격을 비교 검증하여 최종 판매가를 결정한다.',
    ],
    flapTitle: '🧾 디저트 적정 원가율 30% 공식 & 수율(Yield) 계산',
    flapHint: '외식 창업 파티시에의 실전 수익성 분석법',
    flapContent: {
      secretTip: '판매가 산정 공식 = (1개당 총 원가 ÷ 목표 원가율). 예를 들어 원가가 1,500원이고 목표 원가율이 30%이면 권장 판매가는 5,000원입니다.',
      sciencePrinciple: '계량 손실, 반죽 볼 잔류, 굽기 수분 증발로 보통 5~8%의 감량 손실(Bake Loss)이 발생하므로 이를 레시피에 반영해야 정확한 원가가 도출됩니다.',
      goldenRule: '포장재(상자, 리본, 스티커, 방습제) 비용은 제품 원가의 15~20%를 초과하지 않도록 설계하세요.',
    },
    fields: [
      { key: 'recipe', label: '표준레시피와 생산 단위', type: 'textarea', placeholder: '재료 목록, 투입 단위(kg/g), 1배치 생산 가능 수량', fullWidth: true },
      { key: 'materialCost', label: '총 재료비(원)', type: 'number', placeholder: '예: 24500', unitSuffix: '원' },
      { key: 'packageCost', label: '총 포장재료비(원)', type: 'number', placeholder: '예: 4500', unitSuffix: '원' },
      { key: 'yield', label: '정품 완제품 수량(개)', type: 'number', placeholder: '예: 20', unitSuffix: '개' },
      { key: 'unitCost', label: '1개당 개별 원가(원)', type: 'number', placeholder: '예: 1450', unitSuffix: '원' },
      { key: 'price', label: '예상 판매가와 가격 책정 근거', type: 'textarea', placeholder: '권장소비자가격, 원가율(%), 주변 카페 시장 비교 분석', fullWidth: true },
    ],
  },
  {
    id: 16,
    code: '16',
    title: '포장디자인과 패키지 제작',
    moduleGroup: '모듈 4 · 디저트 비즈니스 & 상품화',
    icon: '🎁',
    themeColor: 'violet',
    accentHex: '#7c3aed',
    accentDarkHex: '#6d28d9',
    softHex: '#f5f3ff',
    brief: '제품 보호·위생·이동성에 부산의 색과 이야기를 더해 관광상품 패키지를 완성합니다.',
    goal: '제품 특성에 맞는 지기구조와 재료를 선택하고 부산 이미지를 담은 패키지를 제작한다.',
    photoGuide: '패키지 외관 정면, 개봉한 내부 트레이, 제품을 거치한 상태를 다각도로 촬영하세요.',
    keyQuestions: ['유지류 흡수 방지(식품지) 및 파손 방지 완충 구조는?', '식품위생법 필수 표시사항 기재 여부는?'],
    standardSteps: [
      '1. 디저트의 크기, 충격 취약성, 유지류(버터) 배출 여부를 분석하여 보호 요건을 정립한다.',
      '2. 접착제 없이 조립 가능한 친환경 원터치 접이식 지기구조 전개도를 제도한다.',
      '3. 제품에 직접 닿는 내지는 내유도 인증 식품지를 선택하여 기름 얼룩 번짐을 방지한다.',
      '4. 부산의 명소와 감성을 담은 타이포그래피 및 심볼을 외장 박스에 그래픽 배치한다.',
      '5. 원재료명, 소비기한, 알레르기 유발물질 등 법적 식품 표시사항 스티커를 설계한다.',
      '6. 완성된 패키지에 제품을 넣고 가방 수납 및 도보 이동 테스트를 거쳐 파손 유무를 검증한다.',
    ],
    flapTitle: '🎁 내유도(KIT) 검증 식품지와 안전 지기구조',
    flapHint: '선물용 관광 디저트 패키지 디자인 핵심 요건',
    flapContent: {
      secretTip: '버터 함량이 높은 구움과자는 일반 크라프트지에 닿으면 기름이 얼룩지므로 반드시 식품용 PE 코팅지나 내유도 8등급 이상의 식품지를 사용하세요.',
      sciencePrinciple: '상자 내부 칸막이(트레이)는 제품 크기보다 2~3mm 여유만 두어야 흔들림에 의한 부서짐을 완벽히 차단합니다.',
      goldenRule: '식품 표시사항(원재료, 알레르기 유발물질 알림, 소비기한, 보관방법)은 법적 필수 기재 사항입니다.',
    },
    fields: [
      { key: 'productRisk', label: '제품 특성과 보호 위험도', type: 'textarea', placeholder: '부서짐, 온도 민감도(녹음), 수분 증발, 산화 위험 요인 분석', fullWidth: true },
      { key: 'material', label: '포장 재료와 친환경 요소', type: 'textarea', placeholder: '크라프트지, 사탕수수지, 생분해 필름 등 선택 사유', fullWidth: true },
      { key: 'size', label: '패키지 외경 규격(mm)', type: 'text', placeholder: '가로 × 세로 × 높이 (예: 180 × 120 × 55mm)' },
      { key: 'label', label: '식품 표시사항 점검', type: 'textarea', placeholder: '원재료명, 알레르기 유발물질, 보관방법, 소비기한 표기 점검', fullWidth: true },
      { key: 'moveTest', label: '이동 및 낙하 테스트 결과', type: 'textarea', placeholder: '도보 10분 휴대 및 가방 적재 후 형태 유지 여부', fullWidth: true },
      { key: 'busanStory', label: '부산 이미지 시각화', type: 'textarea', placeholder: '부산의 상징 색채, 심볼, 타이포그래피 적용 설명', fullWidth: true },
    ],
  },
  {
    id: 17,
    code: '17',
    title: '브랜딩과 상품기획',
    moduleGroup: '모듈 4 · 디저트 비즈니스 & 상품화',
    icon: '✨',
    themeColor: 'amber',
    accentHex: '#d97706',
    accentDarkHex: '#b45309',
    softHex: '#fffbeb',
    brief: '대상 고객과 부산 지역성을 바탕으로 브랜드명·핵심가치·시각언어를 하나의 브랜드로 연결합니다.',
    goal: '부산형 디저트의 타깃 고객과 차별점을 정의하고 일관된 브랜드 및 상품기획서를 완성한다.',
    photoGuide: '브랜드 로고, 무드보드, 시제품과 브랜드 태그가 함께 연출된 대표 이미지를 업로드하세요.',
    keyQuestions: ['경쟁 디저트(부산 기념품) 대비 독보적 차별점(USP)은?', '브랜드의 톤앤매너는 일관적인가?'],
    standardSteps: [
      '1. 2030 부산 여행객 및 선물 구매 고객 페르소나의 니즈와 소비 패턴을 분석한다.',
      '2. 부산 로컬 식재료와 스토리텔링을 융합한 핵심 차별점(USP 3가지)을 정의한다.',
      '3. 발음하기 쉽고 기억에 남는 브랜드 네이밍과 한 줄 감성 슬로건을 창작한다.',
      '4. 브랜드 키 컬러, 전용 서체, 그래픽 무드보드를 구축하여 시각 일관성을 확보한다.',
      '5. 단품 판매 및 선물용 4구/8구 선물 세트 라인업 및 가격 전략을 수립한다.',
      '6. 브랜드 기획서로 정리하여 시제품과 함께 상품화 타당성을 최종 검토한다.',
    ],
    flapTitle: '✨ 부산 로컬 USP 도출 & 3초 매혹 슬로건 공식',
    flapHint: '고객의 지갑을 여는 브랜드 아이덴티티 전략',
    flapContent: {
      secretTip: '단순히 맛있는 빵을 파는 것이 아니라 “부산 여행의 기억을 한 입 베어무는 순간”이라는 감성적 경험 가치(Emotional Value)를 제안하세요.',
      sciencePrinciple: 'USP(Unique Selling Proposition)는 1) 로컬 원재료 독점성 2) 시각적 랜드마크 형태 3) 패키지 간편 휴대성 중 1개에 집중할 때 가장 강력합니다.',
      goldenRule: '슬로건은 10자 내외로 쉽고 리듬감 있게 작성해 소비자의 입에 착 감기도록 만드세요.',
    },
    fields: [
      { key: 'target', label: '핵심 타깃 페르소나', type: 'textarea', placeholder: '연령, 관광객 vs 로컬, 선물 구매 상황 및 소비 성향', fullWidth: true },
      { key: 'problem', label: '고객이 원하는 핵심 가치', type: 'textarea', placeholder: '차별화된 부산 선물, 감성적인 비주얼, 보관 편의성 등', fullWidth: true },
      { key: 'brand', label: '브랜드 네이밍 & 브랜드 의미', type: 'text', placeholder: '예: 바다한입 (부산의 파도를 굽다)' },
      { key: 'slogan', label: '한 줄 브랜드 슬로건', type: 'text', placeholder: '소비자에게 기억될 간결하고 명확한 카피라이팅' },
      { key: 'usp', label: '핵심 차별점 3가지 (USP)', type: 'textarea', placeholder: '1) 부산 특산물 원료 2) 독창적 시각 형태 3) 친환경 스토리텔링', fullWidth: true },
      { key: 'productPlan', label: '상품 라인업 및 판매 전략', type: 'textarea', placeholder: '단품 및 선물용 4구/8구 세트 구성, 유통 채널(팝업/온라인)', fullWidth: true },
    ],
  },
  {
    id: 18,
    code: '18',
    title: 'SNS 마케팅과 홍보콘텐츠 제작',
    moduleGroup: '모듈 4 · 디저트 비즈니스 & 상품화',
    icon: '📱',
    themeColor: 'rose',
    accentHex: '#e11d48',
    accentDarkHex: '#be123c',
    softHex: '#fff1f2',
    brief: '목표 고객과 플랫폼 특성에 맞춰 사진·문구·해시태그·행동 유도 문장을 설계합니다.',
    goal: '부산형 디저트의 매력을 3초 안에 전달하는 SNS 카드뉴스 및 숏폼 홍보콘텐츠를 제작한다.',
    photoGuide: '게시용 1:1 정방형 썸네일 또는 9:16 릴스/쇼츠 첫 화면 캡처 이미지를 업로드하세요.',
    keyQuestions: ['피드 스크롤을 멈추게 할 훅(Hook) 요소는?', '자연스러운 방문 및 구매 전환 유도(CTA)는?'],
    standardSteps: [
      '1. 인스타그램 타깃 독자의 관심사와 여행 탐색 행동 특성을 파악한다.',
      '2. 시선을 단숨에 사로잡는 첫 3초 훅(Hook) 헤드라인 카피를 작성한다.',
      '3. 제품의 단면과 만드는 과정의 ASMR을 담은 고화질 사진 및 숏폼 영상을 촬영한다.',
      '4. 장소, 구매 팁, 보관 방법을 친절하게 풀어낸 본문 캡션을 작성한다.',
      '5. 검색 유입을 극대화할 수 있는 핵심 해시태그 15개를 엄선하여 배치한다.',
      '6. “저장해두고 부산 갈 때 확인하세요” 같은 명확한 행동 유도 문장(CTA)을 배치한다.',
    ],
    flapTitle: '📱 릴스 3초 훅(Hook) 공식과 인스타그램 저장(Save) 유도법',
    flapHint: '조회수와 바이럴을 부르는 숏폼 비주얼 앵글',
    flapContent: {
      secretTip: '영상의 첫 1.5초 안에 단면 자르기(Cross-section)나 크림 주르륵 흐르는 샷을 배치해야 사용자가 피드 스크롤을 멈춥니다.',
      sciencePrinciple: '인스타그램 알고리즘은 ‘좋아요’보다 ‘저장하기(Save)’와 ‘공유(Share)’ 가중치가 3배 높습니다. “부산 여행 시 필구 리스트”처럼 소장 가치를 부여하세요.',
      goldenRule: '자연 채광(오전 10시~오후 2시 역광/사광) 아래에서 45도 각도로 촬영할 때 글레이즈 광택이 가장 돋보입니다.',
    },
    fields: [
      { key: 'platform', label: '타깃 플랫폼 & 선정 이유', type: 'text', placeholder: '예: Instagram / 부산 여행객의 비주얼 탐색 선호' },
      { key: 'audience', label: '콘텐츠 타깃 독자', type: 'textarea', placeholder: '부산 주말 여행을 계획 중인 2030 MZ 디저트 마니아', fullWidth: true },
      { key: 'headline', label: '3초 훅킹 헤드라인 (첫 문장)', type: 'text', placeholder: '예: “광안리 바다를 쿠키에 담았습니다. 한 입 베어물면 파도가 펼쳐져요”' },
      { key: 'caption', label: '게시글 본문 스토리텔링', type: 'textarea', placeholder: '재료의 정성, 부산 로컬 감성, 보관 팁, 구매 방법 서술', fullWidth: true },
      { key: 'hashtags', label: '타깃 해시태그 (#)', type: 'textarea', placeholder: '#부산관광고 #MICE외식조리과 #부산디저트 #부산여행선물 #디저트실무 #파티시에', fullWidth: true },
      { key: 'cta', label: '행동 유도 문장 (Call To Action)', type: 'text', placeholder: '예: “게시물을 저장해두고 이번 주말 부산 여행 코스에 추가해보세요!”' },
    ],
  },
  {
    id: 19,
    code: '19',
    title: '부산 시그니처 디저트 팀 프로젝트',
    moduleGroup: '모듈 5 · 캡스톤 프로젝트 & 쇼케이스',
    icon: '👩‍🍳',
    themeColor: 'teal',
    accentHex: '#0d9488',
    accentDarkHex: '#0f766e',
    softHex: '#f0fdfa',
    brief: '팀 역할·일정·시제품 데이터를 공유하고 한 가지 변수를 바꾸어 부산 시그니처 디저트를 개선합니다.',
    goal: '팀원 간 협업으로 프로토타입을 제작하고 데이터와 피드백을 근거로 디저트 품질을 혁신한다.',
    photoGuide: '1차 시제품과 개선된 2차 시제품을 나란히 놓아 비교한 사진을 업로드하세요.',
    keyQuestions: ['팀 내 명확한 분업(총괄/제조/기록/디자인)이 이뤄졌는가?', '1차 피드백에서 발견한 최대 결점은?'],
    standardSteps: [
      '1. 팀원 간 역할(기획총괄, 제조담당, 공정기록, 디자인패키징)을 분담하고 타임라인을 수립한다.',
      '2. 부산 상징 랜드마크나 식재료를 재해석한 1차 프로토타입 디저트를 제조한다.',
      '3. 동료 및 교사로부터 외관, 당도, 식감에 대한 관능 피드백을 수렴하여 데이터화한다.',
      '4. 1차 제품의 최대 결점을 파악하고, 바꿀 핵심 변수 1가지(온도 or 배합비)를 확정한다.',
      '5. 1변수 통제 원칙에 따라 개선된 2차 시제품을 재제조하고 결과를 나란히 비교 관찰한다.',
      '6. 개선 전·후의 데이터를 정리하여 최종 시그니처 디저트 완성을 입증한다.',
    ],
    flapTitle: '👩‍🍳 1회 1변수 통제 법칙(One-Variable Rule)과 피드백 반영',
    flapHint: '체계적인 R&D 제품 개발 프로세스',
    flapContent: {
      secretTip: '개선 시제품을 만들 때 설탕량과 오븐 온도를 동시에 바꾸면 무엇 때문에 식감이 달라졌는지 알 수 없습니다. 반드시 한 번에 1가지 변수만 변경하세요.',
      sciencePrinciple: '팀원 간 피드백을 수용할 때는 “맛있다/별로다” 같은 감상이 아니라 “단맛 4점, 수분감 2점, 향미 5점”처럼 구체적 지표로 수치화해야 합니다.',
      goldenRule: '동료의 비판은 제품을 위한 선물입니다. 개인적 감정을 배제하고 완벽한 시그니처 디저트를 향해 협력하세요.',
    },
    fields: [
      { key: 'team', label: '팀명·팀원·세부 역할', type: 'textarea', placeholder: '팀명 및 기획, 반죽, 오븐, 플레이팅, 기록 담당자', fullWidth: true },
      { key: 'concept', label: '팀 개발 시그니처 콘셉트', type: 'textarea', placeholder: '부산의 어떤 식문화나 랜드마크를 재해석한 디저트인가?', fullWidth: true },
      { key: 'plan', label: '실습 타임라인 & 작업 분장', type: 'textarea', placeholder: '사전 준비 → 계량 → 반죽 → 굽기 → 데코 → 정리 시간 계획', fullWidth: true },
      { key: 'prototype', label: '1차 프로토타입 제작 결과', type: 'textarea', placeholder: '초기 제품의 외관, 식감, 당도, 작업성 평가', fullWidth: true },
      { key: 'feedback', label: '선생님 및 동료 피드백 수렴', type: 'textarea', placeholder: '교사와 동료 학생들의 관능평가 피드백 요약', fullWidth: true },
      { key: 'revision', label: '바꿀 핵심 변수 1가지 (개선안)', type: 'textarea', placeholder: '예: 굽기 온도 10℃ 하향 및 레몬 제스트 5g 추가로 밸런스 개선', fullWidth: true },
    ],
  },
  {
    id: 20,
    code: '20',
    title: '품평회 및 전시·발표',
    moduleGroup: '모듈 5 · 캡스톤 프로젝트 & 쇼케이스',
    icon: '🏆',
    themeColor: 'amber',
    accentHex: '#b45309',
    accentDarkHex: '#92400e',
    softHex: '#fffbeb',
    brief: '전시·시식·발표 결과를 관능평가와 관람객 반응으로 정리하여 최종 개선 방향을 도출합니다.',
    goal: '제품을 위생적으로 전시하고 공정한 품평과 발표를 통해 강점·보완점·최종 포트폴리오를 완성한다.',
    photoGuide: '전시 테이블 전체 셋업, 쇼케이스 연출, 시식 품평회 발표 장면을 종합 촬영하세요.',
    keyQuestions: ['관능평가 5대 요소(외관/향/식감/맛/조화) 점수는?', '향후 산업체 현장 적용 가능성은?'],
    standardSteps: [
      '1. 전시대 온습도와 조명(3000K 웜톤)을 맞추고 위생 덮개와 집게, 알레르기 안내판을 정돈한다.',
      '2. 시식용 포션과 전시용 메인 디저트를 규격에 맞게 아름답게 세팅한다.',
      '3. 제품의 탄생 배경, 부산 스토리텔링, 과학적 공정 개선 과정을 3분 스피치로 발표한다.',
      '4. 심사위원 및 평가단에게 5대 관능평가표를 배부하고 시식을 진행한다.',
      '5. 평가단 질의응답을 성실히 기록하고 관람객의 호평과 지적 사항을 수렴한다.',
      '6. 품평회 종합 결과를 토대로 향후 파티시에로서의 최종 발전 방향을 도출한다.',
    ],
    flapTitle: '🏆 5각 관능평가 분석표와 전문 쇼케이스 연출법',
    flapHint: '20단원을 총결산하는 전문 파티시에 쇼케이스',
    flapContent: {
      secretTip: '디저트 전시 시 조명은 3000K 전구색 웜톤을 제품의 45도 상단에서 비출 때 표면의 광택과 질감이 가장 맛있어 보입니다.',
      sciencePrinciple: '관능평가는 1) 외관(Visual) 2) 아로마(Aroma) 3) 식감(Texture) 4) 미각(Taste) 5) 독창성(Originality)의 5개 축으로 균형도를 측정합니다.',
      goldenRule: '발표할 때는 실패를 어떻게 극복하고 데이터를 축적했는지의 ‘성장 스토리’를 말할 때 청중의 공감을 얻습니다.',
    },
    fields: [
      { key: 'display', label: '전시 위생·쇼케이스 연출 점검', type: 'textarea', placeholder: '쇼케이스 온도 유지, 위생 덮개, 집게, 명찰, 알레르기 안내판 점검', fullWidth: true },
      { key: 'sensory', label: '관능평가 종합 점수 (5점 척도)', type: 'textarea', placeholder: '외관( ), 향기( ), 식감( ), 맛( ), 상품성( ) 평균 점수 및 코멘트', fullWidth: true },
      { key: 'audience', label: '시식 관람객 & 심사위원 반응', type: 'textarea', placeholder: '가장 호평받은 점과 의외의 지적 사항 기록', fullWidth: true },
      { key: 'presentation', label: '발표 시 잘 전달된 핵심 가치', type: 'textarea', placeholder: '제작 의도와 부산 로컬 스토리의 설득력 평가', fullWidth: true },
      { key: 'weakness', label: '최종 보완점 및 아쉬운 점', type: 'textarea', placeholder: '생산 시간, 단가, 유통 보관 중 개선이 필요한 지점', fullWidth: true },
      { key: 'next', label: '향후 파티시에로서의 발전 방향', type: 'textarea', placeholder: '20단원 실습을 마무리하며 유지할 강점과 도전할 신메뉴', fullWidth: true },
    ],
  },
];

export const MODULE_GROUPS = [
  { name: '모듈 1 · 클래식 구움과자 & 전통 퓨전', units: [1, 2, 3, 4] },
  { name: '모듈 2 · 케이크 & 슈 페이스트리', units: [5, 6, 7, 8] },
  { name: '모듈 3 · 쇼콜라 & 특화 디저트', units: [9, 10, 11, 12, 13] },
  { name: '모듈 4 · 디저트 비즈니스 & 상품화', units: [14, 15, 16, 17, 18] },
  { name: '모듈 5 · 캡스톤 프로젝트 & 쇼케이스', units: [19, 20] },
];
